Save only modifed form properties
debezium/debezium-ui pull request #344
Opened 2021-05-05 08:39 UTC by uidoyen

2021-05-05 11:12 UTC, indraraj commented
Tested locally, seems to be working fine. Can you also please convert the properties `Key` (with `.` separated instead of `_`) before passing it to the host UI.

2021-05-05 15:47 UTC, uidoyen commented
> Tested locally, seems to be working fine. Can you also please convert the properties `Key` (with `.` separated instead of `_`) before passing it to the host UI.

Modified accordingly!

2021-05-06 05:34 UTC, indraraj requested changes

2021-05-06 10:43 UTC, uidoyen commented on ui/packages/ui/src/app/pages/createConnector/noValidation/debezium/Properties.tsx
> +      finalConfiguration.set(key.replace(/_/g, "."), value)
Updated accodingly. Thanks for the catch.

2021-05-06 12:37 UTC, indraraj approved these changes

2021-05-06 13:31 UTC, mdrillin approved these changes
lgtm

2021-05-06 13:31 UTC, merged